# Generated by Django 3.2.4 on 2021-09-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('userID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
