# Generated by Django 3.2.4 on 2021-09-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyer',
            new_name='UserBuyer',
        ),
    ]
