# Generated by Django 3.2.4 on 2021-09-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210916_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyer_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('buyer_first_name', models.CharField(default='', max_length=100)),
                ('buyer_last_name', models.CharField(default='', max_length=100)),
                ('buyer_email', models.CharField(max_length=100)),
                ('buyer_password', models.CharField(max_length=100)),
                ('address', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='BuyerModel',
        ),
    ]
