# Generated by Django 3.2.4 on 2021-09-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210916_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='address',
            new_name='buyer_address',
        ),
    ]
