# Generated by Django 3.2.4 on 2021-09-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_address_buyer_buyer_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='buyer_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='buyer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='buyer_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='buyer_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='buyer_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='buyer_password',
            new_name='password',
        ),
    ]
