# Generated by Django 3.2.2 on 2021-09-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210917_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='address',
        ),
        migrations.AddField(
            model_name='buyer',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buyer',
            name='house_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buyer',
            name='locality',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='buyer',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buyer',
            name='zipcode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
