# Generated by Django 3.2.4 on 2021-11-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
