# Generated by Django 3.2.2 on 2021-12-01 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_seller_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
