# Generated by Django 3.2.2 on 2021-12-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_delete_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('SHOP_ID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('house_no', models.CharField(default='', max_length=100)),
                ('locality', models.CharField(default='', max_length=1000)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zipcode', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
