# Generated by Django 3.2.4 on 2021-12-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='mobile',
            new_name='OWNER_MOBILE',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='city',
            new_name='SHOP_CITY',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='house_no',
            new_name='SHOP_HOUSE_NO',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='locality',
            new_name='SHOP_LOCALITY',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='state',
            new_name='SHOP_STATE',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='zipcode',
            new_name='SHOP_ZIP_CODE',
        ),
        migrations.AddField(
            model_name='shop',
            name='SHOP_NAME',
            field=models.CharField(default='', max_length=20),
        ),
    ]
