# Generated by Django 3.2.4 on 2021-12-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20211203_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='OWNER_NAME',
            field=models.CharField(default='', max_length=50),
        ),
    ]
