# Generated by Django 3.2.4 on 2021-11-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('SHOP_ID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('SHOP_NAME', models.CharField(default='', max_length=50)),
                ('SHOP_OWNER_USERNAME', models.CharField(max_length=100)),
                ('SHOP_OWNER_NAME', models.CharField(max_length=50)),
            ],
        ),
    ]
