# Generated by Django 3.2.2 on 2021-12-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='SHOP_NAME',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='SHOP_OWNER_NAME',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='SHOP_OWNER_USERNAME',
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='house_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='locality',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='shop',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='zipcode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
