# Generated by Django 3.2.2 on 2021-12-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211201_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
