# Generated by Django 3.2.2 on 2021-10-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('items', models.CharField(max_length=5000)),
                ('user_id', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=2000)),
                ('total_items', models.CharField(max_length=10)),
                ('total_amount', models.CharField(max_length=20)),
                ('discount', models.CharField(max_length=10)),
                ('order_status', models.CharField(max_length=50)),
            ],
        ),
    ]
