# Generated by Django 3.2.2 on 2021-11-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211018_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracker',
            fields=[
                ('oid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('order_status', models.CharField(default='', max_length=100)),
                ('order_status_desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
