# Generated by Django 3.2.2 on 2021-11-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordertracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracker',
            name='trackingid',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ordertracker',
            name='oid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
