# Generated by Django 3.2.2 on 2021-11-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211105_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracker',
            name='order_datetime',
            field=models.CharField(default='', max_length=20),
        ),
    ]
