# Generated by Django 3.2.4 on 2021-12-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_ordertracker_order_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_id',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
