# Generated by Django 3.2.1 on 2021-06-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EshopProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT_IMAGE', models.ImageField(default='', upload_to='products_image')),
                ('PRODUCT_BRAND', models.CharField(default='', max_length=50)),
                ('PRODUCT_TITLE', models.CharField(default='', max_length=100)),
                ('PRODUCT_DESC', models.CharField(default='', max_length=300)),
                ('PRODUCT_CATEGORY', models.CharField(default='', max_length=100)),
                ('PRODUCT_PRICE', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
