# Generated by Django 3.2.2 on 2021-06-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eshopproducts',
            name='PRODUCT_SERIES',
            field=models.CharField(default='', max_length=100),
        ),
    ]
