# Generated by Django 3.2.4 on 2021-12-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_eshopproducts_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='eshopproducts',
            name='SOLD_BY',
            field=models.CharField(default='', max_length=20),
        ),
    ]
