# Generated by Django 3.2.4 on 2021-12-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_eshopproducts_sold_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eshopproducts',
            name='SOLD_BY',
            field=models.CharField(default='', max_length=200),
        ),
    ]
